/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Exceptions.NotASCIIException;
import compiler.Exceptions.UnrecognisedTokenException;
import compiler.Lexer.Lexer;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class Compiler {

  public static void main(String[] args) {
    try (Reader reader = new FileReader(args[1])) {
      Lexer lexer = new Lexer(reader);
      while (lexer.hasNext()) {
        System.out.println(lexer.getNextSymbol());
      }
    } catch (IOException | NotASCIIException | UnrecognisedTokenException e) {
      throw new RuntimeException(e);
    }
  }
}