name: Java CI with Gradle

on:
  push:
    branches: [ "parserv3","parserv4" ]
  pull_request:
    branches: [ "parserv3","parserv4" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check Java and Gradle version
        run: |
          java -version
          ./gradlew --version

      - name: Verify test files
        run: |
          echo "Verifying test files"
          ls -R test/TestFile

      - name: Clean Gradle cache
        run: ./gradlew clean

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test --tests "TestSuite"

      - name: Upload test reports if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/
